name: Auto-update term
run-name: Update classroom term by @ucsd-its-sd
on:
    workflow_dispatch:
    schedule:
        # Run at 06:00, 12:00, 15:00 every day
        # Copy of existing schedule from macserver
        - cron: "0 7 * * *"
jobs:
    scrape:
        runs-on: ubuntu-latest
        steps:
            - name: Set default branch name to `main`
              run: git config --global init.defaultBranch main
            - name: Check out main repo
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GH_TOKEN }}
            - name: Run `autoterm.sh`
              run: |
                  bash ./autoterm.sh
